image: node:latest

stages:
  - build
  - unit_test
  - integration_test

cache:
  paths:
    - node_modules/

install_dependencies:
  before_script:
    - apt-get update -qq && apt-get --yes install yarn
  stage: build
  script:
    - yarn install
  only:
    - merge_requests

unit_test:
  stage: unit_test
  script: yarn run test
  only:
    - merge_requests

integration_test:
  stage: integration_test
  services:
    - name: postgres:12-alpine
      alias: postgres
  script: yarn run test:integration
  only:
    - merge_requests
  variables:
    POSTGRES_DB: taskmanagement_test
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: changeme
    PGDATA: "/data/postgres"
    POSTGRES_INITDB_ARGS: "--encoding=UTF8 --data-checksums"
